project:
  type: website

website:
  page-navigation: true
  title: "Preparing to Teach"
  description: "Preparing to Teach - One-day workshop to prepare current and recent graduate students for a future role as faculty responsible for teaching statistics and data science to undergraduate students across a variety of disciplines."
  repo-url: https://github.com/mine-cetinkaya-rundel/preparing-to-teach-web
  repo-actions: [issue]

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Mine Çetinkaya-Rundel & Allison Theobold"
    background: "#D9E3E4"

  sidebar:
    logo: "images/hex.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/mine-cetinkaya-rundel/preparing-to-teach-web
        text: "GitHub repository"
      - icon: email
        href: mailto:atheobol@calpoly.edu
        text: "Email the organizers"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: apply.qmd
        text: Apply
      - href: agenda.qmd
        text: Agenda
      - href: presenters.qmd
        text: Presenters
      - href: resources.qmd
        text: Resources
      - href: past-workshops.qmd
        text: Past Workshops

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple

editor: visual