project:
  type: website

website:
  page-navigation: true
  title: "Preparing to Teach"
  description: "Preparing to Teach - One-day workshop to prepare current and recent graduate students for a future role as faculty responsible for teaching statistics and data science to undergraduate students across a variety of disciplines."
  site-url: https://preparingtoteach.org/
  repo-url: https://github.com/mine-cetinkaya-rundel/preparing-to-teach-web
  repo-actions: [issue]

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Mine Çetinkaya-Rundel & Allison Theobold"
    background: "#D9E3E4"

  navbar:
    background: "#D9E3E4"
    align: center
    collapse-below: lg
  
    right:
      - icon: github
        href: https://github.com/mine-cetinkaya-rundel/preparing-to-teach-web
      - icon: email
        href: mailto:atheobol@calpoly.edu

    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Apply"
        href: apply.qmd
      - text: "Agenda"
        href: agenda.qmd
      - text: "Presenters"
        href: presenters.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "Past Workshops"
        href: past-workshops.qmd

   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple

editor: visual