---
title: "Call recap: Your first year as a faculty member"
author: Allison Theobold
date: "2019-11-21"
---

The topic of our November 21, 2020 call was first year as a faculty member.
The call was attended by three mentors (Beth Chance, Ulrike Genschel,and Allan Rossman), and four mentees (Allison, Joyce, Abhishek, and Asli).

**Question:** What to expect during your first year as a faculty member.

Abhishek Chakraborty (in his first year at Lawrence University)

-   Unexpected events during the first year of teaching:
    -   **lots** of time spent prepping teaching material (twice what was expected)
    -   creating assignments took nearly an entire day
    -   difficulties choosing *what* to teach\
    -   learning about the dynamics of classes
    -   taught 2 new courses, 1 fall and 1 spring
-   To support faculty in choosing what to teach and creating assignments, the department provided:
    -   shared materials from other colleagues
    -   course descriptions to follow
        -   flexibility to add/emphasize topics important to him/students
        -   flexibility to spend additional time where needed (e.g. hypothesis testing, and confidence intervals)

**Question:** What does data science mean?
What are the expectations of teaching positions that request/prefer experience with data science?

-   Suggestions:
    -   Look at what the department teaches, and the descriptions of the courses
    -   Consider whether you would envision teaching those courses
    -   Consider what statistical languages you are comfortable teaching in
-   At Lawrence they are proposing a minor in statistics/data science
    -   As a new faculty Abhishek helped to write the proposal for the minor
    -   The minor is interdisciplinary with Computer Science
    -   The minor encompasses 6 courses: 200-level Intro to `R`, 200-level Statistics for Data Science, Machine Learning, Bayesian Methods, Mathematical Statistics, and an Interdisciplinary capstone
    -   Some of the courses are new for the minor and Abhishek collaborated in creating the courses and choosing the level at which they are taught (e.g Machine Learning is a 200-level course with a prereq of either 1 CS course or 1 Math course)

**Question:** Joyce was asked to potentially teach "topic" courses for businesses outside of academia.
Do others have experiences teaching these types of courses?
What should she consider when deciding whether to teach them and what topics to teach?

-   Suggestions:
    -   Know what backgrounds your participants have
    -   Understand what they expect to get out of the course
    -   Communicate what is plausible for you to accomplish with the time you are give, since they will likely expect too much
    -   Consider what your time is worth, especially as you begin/finish your dissertation

**Question:** What are people's experiences reaching out to companies for projects to use for undergraduate research or statistical consulting?

-   Suggestions:
    -   Make use of the alumni association for connections to graduates of the university who have businesses in the area
    -   Look into non-profit organizations in the area
    -   Find a contact for the large companies in the area to begin conversations

**Question:** (Ulrike to Abhishek) As a new faculty, what else have you spent your time on?

(Abhishek)

-   If you keep your door open, students will come!
-   Department meetings
-   Revisions to the major
-   Creating the statistics/data science minor
-   Decided to do *no* research for the first term and to instead focus on teaching
-   Will start advising students during second year
-   Prepping old courses is far less time intensive
-   Doing independent study with a student during the winter term
-   Mentor says to "always think about giving yourself a break"

(Ulrike)

-   Expect to serve on committees
    -   These are low loads for new faculty
    -   Possibility of serving on curriculum advisory committee(s)
-   There is a long-term benefit to doing things for yourself!
-   Make connections with other young faculty at a similar stage in their career

(Alan)

-   Don't try to do everything!
-   You don't need to teach the perfect course the first time!
    -   The first time, try to do a competent job.
    -   The second time, make improvements.
    -   The third time the course should be closer to what you'd ideally want.
-   Set realistic expectations for yourself!

**Question:** What are considerations to make when proposing a department "flip" a course which a large number of non-tenured faculty teach?

(Alan)

-   Make sure you have buy-in from senior people in the department
-   Be empathetic on instructor's time--they are likely teaching a large number of courses
-   Understand how much instructors are teaching and where--it is possible they are teaching at multiple colleges/universities
-   Support instructors by providing materials they can use in their classroom
-   Consider the client disciplines the course(s) service, and include faculty from those department(s) in the conversations

(Ulrike)

-   Invite the instructors to contribute in the changes

(Asli)

-   To support changing the Introductory Statistics course, she:
    -   brought in articles supporting the changes she was proposing
    -   made sure the process feel team oriented
