---
title: "Call recap: Remote teaching"
author: "Allison Theobold"
date: "2020-04-21"
---

The topic of our April 21, 2020 call was remote teaching.
We had a very productive call with participation from four mentors (Mine Çetinkaya-Rundel, Beth Chance, Nick Horton, Allan Rossman), and nearly ten mentees -- all participants from PTT 2019.

The main advice that came out of the conversations surrounding remote teaching focused on connecting with students, both as individuals and as groups.

Below we share more detailed notes from the discussion in Q&A format.

**If courses in the fall are entirely online, how can you build a classroom community with students who have never met each other?**

-   Spend more time at the beginning of the semester/quarter/course building a community, using interactive tasks.

-   At beginning of course you could potentially meet for short periods of time \~15 minutes, where students can interact with one another and you.

-   Keep in mind the time differences for non-domestic students!
    Don't require to attend in-person at 3am!

**What are people's preferences for recorded versus live lectures?**

-   Recorded lectures, like in-person lectures, are not very effective.
    Try to find ways to interact with the students and have them interact with each other, such as students peer reviewing each other's work.

-   Again, if you are considering synchronous teaching, be mindful of the time zone differences for students.

-   If you expect students to be reading the textbook, provide them with guidance on how/what to read.
    This task may not come naturally to many students.

-   You can pre-record some (but not all) materials.
    This would allow for a remote classroom feeling similar to a "flipped" classroom.

-   Break-out rooms may be a tool to consider for group work, but you may need to "peak in" on the rooms and encourage students to work together and/or stay on task.

-   Keep in mind that student's spaces and/or technology may not be great and may hinder them from being able to contribute to a group discussion the way you may have originally envisioned.

**Is it appropriate to force students to turn on their video?**

-   Again, students may have limitations regarding the spaces they use to watch class and the computers they use to participate.

-   There may be students who watch class from their carport/garage, because it is the quietest place for them to watch.

-   If you turn-on the option that allows for students to rename themselves, then they can add "can't unmute" to the end of their name.
    This lets you know why students are not sharing their audio/video.

**How do redirect students to use a discussion board to post their questions, so aren't overwhelmed with a large volume of student emails?**

-   You can make a policy at the start of the course that all non grade related questions will only be answered on the discussion board, *not* through email.

-   Students may not know whether their question is "grade related" and will send you an email.
    You can respond asking for them to post the question on the discussion board and incentivize them by saying that you will respond immediately.

-   You can motivate a student to post on the discussion board by making it extra work for them.
    For example, you could require that a student post their question and a summary of your response to the discussion board, if you answer their question through email.

**How do you prevent students from just working alone?**

*on group projects*

-   You can randomly assign groups, and hope that students will work together.

-   For group projects you can have group evaluations, so each group member knows they will be evaluated on their participation.

-   Blackboard allows for file exchanges!
    Some instructors have found that groups of three are the magic number.
    Larger groups tend to leave people behind.
    You can see who contributed what files to Blackboard, as a proxy to student involvement.

*on group work*

-   Adding time for groups to talk about a formative assessment (e.g. readiness assessment tests) before they submit it can help boost group member involvement.

-   As an instructor, you can go into breakout rooms to help facilitate group discussions and show student how to share content.

-   Explicitly show students how to use the platform you are using, don't just assume they know how to use it!

**What are tools instructors have used for students to work together on coding tasks?**

-   GitHub + RStudio Cloud

-   Teamviewer + RStudio Server, allows for a team environment that feels Google Doc like.

-   `livecode` package will allow students to follow along while you code.
    Students can copy and paste the code you are running, and run it locally instead of just following along.

**What are some assessment strategies instructors have used? What about high stakes exams?**

-   Can use LockDown Browser (Respondus) to ensure students aren't Googling exam questions.

-   Can take exam on Zoom, to allow students to send you live questions for clarification.

-   Respondus Monitor monitors student's webcams to monitor their eye activity.

-   When you are writing exam questions, type the question into Google!
    Then you can see what answers students will see if they search.
    Try to make your exam questions less Google-able, by adding additional steps they would need to take in order to find an answer.

**Have instructors used oral exams for final exams?**

-   Some instructors have done this for in person exams, but not online.

-   These environments are very stressful for students, so disentangling their understanding from their stress and emotions would be very difficult.
    Thus, this environment would require a great deal of thought on what a \_\_ grade looks like.

-   Consider if this style of an exam would bring students even more stress, when already under the stress of a global pandemic.
